### ISSUE TITLE
divid core wallet not updated

### ISSUE THREAD

**Issue by redno2** [DiviProject/Divi#201]
### Description

I've upgraded my masternode to the latest version 
https://github.com/DiviProject/Divi/releases/tag/v1.1.2
but cannot start it after upgraded. Seem  that the core version on the wallet stay to the 1.0.8, and it's probably incompatible !? I try to start from console on the wallet, it say MN successful started, but not really

An on my MN I've 
```
# ./divi/bin/divi-cli getmasternodestatus 
error: {"code":-1,"message":"Masternode not found in the list of available masternodes. Current status: Not capable masternode: Hot node, waiting for remote activation."}
```

### Environment

Ubuntu 18.04.4

Please update your documentation for the upgrading procedure too, for the own MN

Thanks.

**Comment by galpHub** [comment]
Hey @redno2,
The masternode configuration on the node actually hosting the masternode now requires that the config line stored on the controlling wallet side be also added in the masternode.conf file

**Comment by redno2** [comment]
thank you, but which config line you talking about ?

**Comment by 7h3v01c3** [comment]
> 
> 
> thank you, which config line you talking about ?

One VPS
1. Stop divid 
2. Open your data directory
.divi 
3.. rename the masternode.conf to masternode.backup

Go back to local install
4. Stop Divi Desktop or Divid
5. Open your data directory (Choose your OS version)

Windows: C:\Users<your-username>\AppData\Roaming\DIVI

OSX: ~/Library/Application\ Support/DIVI

Linux: /home/.divi

6. Make a copy of the masternode config and move to your VPS .divi directory from step 2.
(make sure the copy you move in is named masternode.conf)

7. Restart Local install of Divi

8. Restart divi on VPS

9. Send startmasternode command the local install


**Troubleshooting if it downs start then the masternode was corrupt in the copy over or if you transcribed your details, double check or do it again**

**Comment by redno2** [comment]
Ok. thank you @galpHub & @7h3v01c3 , that's work. Maybe useful to add it to your official documentation, for those guys like me where use there own servers.
Why you need to put the master node private key to the masternode host config node, now ? that's weird and might be a security issue

**Comment by 7h3v01c3** [comment]
> Ok. thank you @galpHub & @7h3v01c3 , that's work. Maybe useful to add it to your official documentation, for those guys like me where use there own servers.
> Why you need to put the master node private key to the masternode host config node, now ? that's weird and might be a security issue

That's an excellent and supper important realization. 

You are correct; Divi is moving in a different direction. Divi's entire philosophy, "Crypto Made Easy" is for New Coiners and New Users, so manual setups as the whole, don't drive our evolution. Eventually, we will further progress away from the old school methods into the new, making, and sharing new paths in the never-ending effort to remove barriers to entry.

However, after all, is said, we know there are many reasons why even the most experienced user may want to participate in Divi. We embrace everyone. You can and will be able to deploy a manual setup even in the future.

So I agree it will need to be something that may be better documented but will always be the last in line for documentation because the philosophy focuses on ease of use.

Now your second point - no the key you are talking about is not a true PK and hast so no relation to coins, values, or otherwise.  

But good thoughts brother we appreciate you input

**Comment by 7h3v01c3** [comment]
Resolved with masternode.conf instructions
