### ISSUE TITLE
estimateFee does not work after update to 3.0.0

### ISSUE THREAD

**Issue by fmira21** [DiviProject/Divi#236]
Hi guys!

I am hosting the DIVI node deployed with Blockbook.
After the update, I cannot address to the `estimateFee` endpoint.
Has it been fully deprecated?
Is there any workaround?

Thank you in advance!

**Comment by 7h3v01c3** [comment]
Hi there!

We have discontinued the use of the estimatefee function as we now have simplified fees to a  fixed fee rate that takes into account the size of the transaction. It is necessary to develop a separate calculation method without relying on deprecated features that utilize the mempool. The fixed fee rates eliminate the need for such features. If future interest is high there may be some consideration in adding a different process to estimate fees, but this is not currently on the roadmap, because there is no need to estimate but calculate.

And even better you can see how in the Minimum Fee Coin Selection Algorithm

https://github.com/DiviProject/Divi/blob/9e2f76c4408380e72f6e369fff3882ed13667a42/divi/src/MinimumFeeCoinSelectionAlgorithm.cpp
