### ISSUE TITLE
Divi Desktop seems to get corrupted if macOS is restarted

### ISSUE THREAD

**Issue by brindy** [DiviProject/Divi#97]
This happens to me quite often.  After restarting macOS for some reason when then launch Divi Desktop it cannot synchronise and I have to clear the cache to get it to work.

The app should detect a system shutdown and close itself cleanly.

**Comment by 99darwin** [comment]
Moved to the correct repo

**Comment by 7h3v01c3** [comment]
Unfortunately its not the app that is getting corrupt.

It is the database or data sets that are corrupting - I see this mostly on users of WIFI, not on Ethernet connections. Every few seconds the daemon is syncing the database - it is hard to corrupt the database  or secondary data sets but not impossible. My guess is you are using wifi and you are bouncing from the access point to access point(or its pinging and trying to connect - therefore dropping a packet or many for the datasets) If this happens all day long - you will end up with some data set corrupt, blocks, mncache, peers something.  

Divi knew this was a potential issue  -  so they re-configured the wallet to have tools accessible for users who experienced such a case. In most cases - blockchain wallets if you blow your data, you have to manually got to the command line and fix or dig deep into hidden files to fix. This is not crypto made easy - so divi made three tools for helping and clear cache is one of them and the other is rescan(-reindex) available even in a corrupt wallet(not available on any other wallet with a shutdown issue). If the clear cache is the only one that works - then you have more than just a little data corruption. It is a local network issue, not a DIVI issue. 
When the Divi Desktop issues the stop command to the daemon - it stops everything gently - which closes off those current data sets. Some of that data is needed only during certain times like peers.dat. It is also updating peers.dat every so often. However if that becomes corrupt from a network connection and you restart the wallet(daemon) the daemon cannot connect because the peers' data is corrupt - hence the reason for the clear cache.

Try fixing your wifi to have priotization of connections

see if that fixes
